add option to not build ssl 1.1.0 ulinux version

diff --git a/Unix/configure b/Unix/configure
--- a/Unix/configure
+++ b/Unix/configure
@@ -321,6 +321,9 @@ do
         disable_ssl_0_9_8=1
         ;;
 
+    --disable-ssl-1.1.0)
+        disable_ssl_1_1_0=1
+        ;;
 
     *)
         echo "$0: unknown option:  $opt"
@@ -520,11 +523,13 @@ if [ "$enable_ulinux" = "1" ]; then
         exit 1
     fi
 
-    echo "checking for local installation of openssl version 1.1.0 on system ..."
-    if [ `uname -m` = "x86_64" -a ! -d "$openssl110_dir" ]; then
-        echo "did not find ${openssl110_dir}, which is required."
-        echo "You must install a local copy of OpenSSL version 1.1.0 to build successfully."
-        exit 1
+    if [ "$disable_ssl_1_1_0" != "1" ]; then
+        echo "checking for local installation of openssl version 1.1.0 on system ..."
+        if [ `uname -m` = "x86_64" -a ! -d "$openssl110_dir" ]; then
+            echo "did not find ${openssl110_dir}, which is required."
+            echo "You must install a local copy of OpenSSL version 1.1.0 to build successfully."
+            exit 1
+        fi
     fi
 fi
 
